[tool.poetry]
name = "poetry-check-monorepo"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
poetry = "1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"